### ISSUE TITLE
Force update problem

### ISSUE THREAD

**Issue by amismailphp** [zelenin/yii2-slug-behavior#11]
Hi, when i host my application, 'forceUpdate' => true, gives me internal server error.
I not really catch the problem, but it occurs in some hosts not others.
Thanks in advance

**Comment by zelenin** [comment]
I think forceUpdate will work with Yii 2.0.2. Try update.

**Comment by amismailphp** [comment]
sorry, this issue occurs due to the behavior at all, again, it doesn't appear in all hosts, it may depends on host configuration or needs change rewrites (.htaccess)

**Comment by zelenin** [comment]
see php logs for error.

**Comment by amismailphp** [comment]
2015-01-27 17:43:18 [197.162.117.199][1][-][error][yii\web\HttpException:404] exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "product/cgi-sys/images/404bottom.gif".' in /home/wthub/public_html/lapalette/_protected/vendor/yiisoft/yii2/base/Module.php:461
Stack trace:
#0 /home/wthub/public_html/lapalette/_protected/vendor/yiisoft/yii2/web/Application.php(83): yii\base\Module->runAction('product/cgi-sys...', Array)
#1 /home/wthub/public_html/lapalette/_protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /home/wthub/public_html/lapalette/backend/index.php(18): yii\base\Application->run()

**Comment by amismailphp** [comment]
It may be a complicated problem, i really cant catch it, OK, if you noticed  the problem easily, please reply, or i may save slug by hand.

**Comment by zelenin** [comment]
I don't see that it's behavior issue.
Am I right?

**Comment by amismailphp** [comment]
It doesn't appear in log, but when i remove the behavior, it works without errors on create or update

**Comment by zelenin** [comment]
which is yii version?

**Comment by amismailphp** [comment]
i traced my code, the problem occurs in save() method

**Comment by amismailphp** [comment]
oh, i can't detect version, but its the first release, and i use your extension since 2 months

**Comment by zelenin** [comment]
version in BaseYii,php 
https://github.com/yiisoft/yii2/blob/master/framework/BaseYii.php#L96

**Comment by amismailphp** [comment]
2.0.0

**Comment by zelenin** [comment]
i write early that forceUpdate work with Yii 2.0.2. Sorry that it's not in readme.
Update Yii to version 2.0.2.

**Comment by amismailphp** [comment]
OK, many thanks for your Patience.

**Comment by zelenin** [comment]
Thanks for issue. That's important too.
