### ISSUE TITLE
Ошибка "Ответ нулевой длины"

### ISSUE THREAD

**Issue by almix** [zelenin/yii2-slug-behavior#15]
локально работает, но на сервере ошибка:

Запрошенный URL не может быть доставлен
Произошла следующая ошибка:
Ответ нулевой длины
Кэш не получил никаких данных в ответ на этот запрос.

**Comment by zelenin** [comment]
расширение не работает ни с урлом ни с кэшем.

**Comment by almix** [comment]
заработало если оставить в опциях:
 'transliterateOptions' => 'Russian-Latin/BGN; Any-Latin; NFD;'

думаю транслитератор не срабатывал
