### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by mskayali** [zelenin/yii2-slug-behavior#16]
<p>Hi there... I need an urgent help. Here is an exception error which occur after I press submit button.</p> 

<hr>
<pre>
exception 'yii\base\ErrorException' with message 'Call to a member function transliterate() on a non-object' in /var/www/map2heal/vendor/zelenin/slugifier/Slugifier.php:76
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
</pre>

**Comment by zelenin** [comment]
is intl extension turn on?

**Comment by mskayali** [comment]
yes php intl turned on..

**Comment by zelenin** [comment]
is transliterateOptions incorrect?

**Comment by zelenin** [comment]
i've add some checks and exceptions. Update
