### ISSUE TITLE
Transliterate on russian

### ISSUE THREAD

**Issue by loveorigami** [zelenin/yii2-slug-behavior#17]
После обновления заметил, что перестала "нормально" работать транслитерация.
```php
                'class' => \Zelenin\yii\behaviors\Slug::className(),
                'slugAttribute' => 'slug',
                'attribute' => 'name',
                'ensureUnique' => true,
                'replacement' => '-',
                'lowercase' => true,
                'immutable' => true,
                'transliterateOptions' => 'Russian-Latin/BGN; Any-Latin; NFD;'
```
в предыдущих версиях вводил `пляжи`,  получал  `plyazhi`
сейчас получаю `plazi`

пробовал разные transliterateOptions - никакого результата.
может, нужен еще какой-то параметр?

**Comment by zelenin** [comment]
какая версия?
сейчас используется https://github.com/zelenin/slugifier
тещу на нем (0.0.3) - plyazhi. Попробуйте собрать проект на нем

```php
require_once __DIR__ . '/vendor/autoload.php';

$string = 'пляжи';
$slugifier = new \Zelenin\Slugifier\Slugifier($string);
$slugifier->transliterateOptions = 'Russian-Latin/BGN; Any-Latin; NFD;';
$slugifier->replacement = '_';
$slugifier->lowercase = false;
$slug = $slugifier->getSlug();

echo $slug;
```

если plazi, то дело в intl

**Comment by loveorigami** [comment]
Самое интересное, что такой код у меня тоже выводит `plyazhi`.
![02](https://cloud.githubusercontent.com/assets/98164/9407806/8043f28c-4815-11e5-93f5-7113febe874b.jpg)

А вот если через поведение (с наcтройками, как выше), то получаю `plazi`...

![01](https://cloud.githubusercontent.com/assets/98164/9407821/a0f9837a-4815-11e5-9d44-3a1e70b644b3.jpg)

**Comment by zelenin** [comment]
https://github.com/zelenin/yii2-slug-behavior/blob/master/Slug.php#L123

нет мыслей.

**Comment by loveorigami** [comment]
Я тоже до этого дошел ). Пишу
```php
    private function slugify($string, $replacement = '-', $lowercase = true)
    {
        $slugifier = new Slugifier($string);

        echo $this->transliterateOptions;
```
получаю - `Russian-Latin/BGN; Any-Latin; NFD; `

дебажу дальше...

**Comment by loveorigami** [comment]
вот здесь
https://github.com/zelenin/slugifier/blob/master/Slugifier.php#L75
у меня $this->transliterateOptions; пустая.

**Comment by zelenin** [comment]
Да, конечно же, ошибка https://github.com/zelenin/yii2-slug-behavior/blob/master/Slug.php#L126
должно быть !== null. Проверьте и пофикшу.

**Comment by loveorigami** [comment]
нашел
https://github.com/zelenin/yii2-slug-behavior/blob/master/Slug.php#L126
должно быть
 if ($this->transliterateOptions !== null) {

**Comment by zelenin** [comment]
fixed https://github.com/zelenin/yii2-slug-behavior/pull/18
