### ISSUE TITLE
Срабатывание при фильтрации

### ISSUE THREAD

**Issue by maxyc** [zelenin/yii2-slug-behavior#19]
Во-первых спасибо за компонент. Удобный и простой. 
Во вторых, словил глюк. Как отключить такое поведение?

Когда пытаюсь отфильтровать в гриде, у меня срабатывает этот бехевиор и думает, что я собираюсь добавлять в базу новое значение.

**Comment by zelenin** [comment]
следуя стандартным практикам: создаем Search-модель с пустым behaviors(). Не относится к данному расширению.
