### ISSUE TITLE
Ь знаки

### ISSUE THREAD

**Issue by jb-studio** [zelenin/yii2-slug-behavior#21]
Спасибо за расширение!
Можно ли сделать чтоб вместо мягких знаков не ставилось - 
а просто убирался он и все?

**Comment by zelenin** [comment]
https://github.com/zelenin/yii2-slug-behavior/blob/master/Slug.php#L49
можно задать свое правило. навскидку синтаксис не подскажу - потестите на основе ссылки из кода.
