### ISSUE TITLE
Behavior doesn't work after upgrading yii2 to 2.0.6

### ISSUE THREAD

**Issue by limion** [zelenin/yii2-slug-behavior#22]
After upgrading yii2 to 2.0.6 I'm getting the following error:
Access level to Zelenin\yii\behaviors\Slug::validateSlug() must be protected (as in class yii\behaviors\SluggableBehavior) or weaker

**Comment by zelenin** [comment]
Method is private in 2.0.6. Not protected.
https://github.com/yiisoft/yii2/blob/89eb3dff144cffeb1b72107a235afc345ac2320e/framework/behaviors/SluggableBehavior.php#L181

**Comment by limion** [comment]
Sorry 2.0.7. In 2.0.7 method is private.

**Comment by limion** [comment]
This information confused me: https://github.com/yiisoft/yii2/blob/2.0.7/framework/UPGRADE.md
It says that validateSlug() was changed to protected in 2.0.6.

**Comment by zelenin** [comment]
use last dev-version. it's preparing version for 2.0.7. I will tag it as stable soon.

**Comment by limion** [comment]
Ok, thank you.
