### ISSUE TITLE
Ошибка "Access level must be protected"

### ISSUE THREAD

**Issue by DukeNsk** [zelenin/yii2-slug-behavior#23]
После недавнего апдейта фреймворка стали выскакивать ошибка для двух методов:
Access level to Zelenin\yii\behaviors\Slug::validateSlug() must be protected
Access level to Zelenin\yii\behaviors\Slug::generateUniqueSlug() must be protected (as in class yii\behaviors\SluggableBehavior) or weaker

Лечится исправлением уровня доступа методов поведения validateSlug и generateUniqueSlug на protected

**Comment by zelenin** [comment]
https://github.com/zelenin/yii2-slug-behavior/issues/22
